project_name: pulumi-kubernetes-operator

builds:
  - ldflags:
      - -X github.com/pulumi/pulumi-kubernetes-operator/version.Version={{.Tag}}
      - -w -extldflags "-static"
    flags:
      - -a
      - -tags
      - netgo
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/manager/main.go
    binary: pulumi-kubernetes-operator

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      amd64: x86_64
      arm64: aarch64
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{.Commit}}"

changelog:
  sort: asc

release:
  github:
    owner: pulumi
    name: pulumi-kubernetes-operator
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
    - "pulumi/{{ .ProjectName }}:latest"
    - "pulumi/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.label-schema.build-date={{.Date}}"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.vcs-ref={{ .ShortCommit }}"
      - "--label=org.label-schema.vcs-url='{{ .GitURL }}'"
  
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile-arm64
    image_templates:
    - "pulumi/{{ .ProjectName }}:latest"
    - "pulumi/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.label-schema.build-date={{.Date}}"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.vcs-ref={{ .ShortCommit }}"
      - "--label=org.label-schema.vcs-url='{{ .GitURL }}'"